apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitsync-alertscripts-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitsync-externalscripts-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: gitsync
  namespace: test
spec:
  containers:
  - name: gitsync
    image: localhost:32000/my/gitrepo-todir-sync:test
    # imagePullPolicy: IfNotPresent
    imagePullPolicy: Always
    volumeMounts:
    - name: externalscripts
      mountPath: /usr/lib/zabbix/externalscripts
    - name: alertscripts
      mountPath: /usr/lib/zabbix/alertscripts
    ports:
    - containerPort: 80
    env:
      - name: REPO_DIR_DSTS
        value: /usr/lib/zabbix/externalscripts /usr/lib/zabbix/alertscripts
      - name: REPO_URI_SRCS
        value: https://github.com/MYREPO/mon-externalscripts.git https://github.com/MYREPO/mon-alertscripts.git
      - name: INTERVAL
        value: "60"
      - name: BRANCH
        value: master
      - name: CHMOD
        value: "chmod ugo+x"
      - name: CHMOD_EXCLUDE
        value: .md\|.txt\|.go
      - name: REPO_USER
        value: myuser
      - name: REPO_PASS
        valueFrom:
          secretKeyRef:
            name: test
            key: test_gitrepo_pat
  volumes:
  - name: alertscripts
    persistentVolumeClaim:
      claimName: gitsync-alertscripts-pvc
    - name: externalscripts
    persistentVolumeClaim:
      claimName: gitsync-externalscripts-pvc
